"""
players.py
----------
Add NBA players here. Each player is a dictionary with their current team
and season statistics. The projection engine will use these stats to
calculate prop projections.

Data source
-----------
Stats are sourced from Props Madness (https://propsmadness.com).
Example player reference: https://propsmadness.com/?player=204&match=5980

Roster template columns
------------------------
Team | Name | Pos | GP | PTS | FGM | FG% | 3PM | 3PA | 3P% | FTM | FT% | Reb | Ast | STL | BLK | TO

Field reference
---------------
Required fields
~~~~~~~~~~~~~~~
team                      : str   - Current NBA team (e.g. "Boston Celtics")         → Team
name                      : str   - Player's full name                                → Name
position                  : str   - Primary position: PG, SG, SF, PF, or C           → Pos
games_played              : int   - Games played this season                          → GP
points_per_game           : float - Average points per game                           → PTS
fgm                       : float - Field goals made per game                         → FGM
field_goal_pct            : float - Field goal percentage (0.0 – 1.0)                 → FG%
three_pointers_per_game   : float - 3-pointers made per game                          → 3PM
three_pointers_attempted  : float - 3-point attempts per game                         → 3PA
three_point_pct           : float - Three-point percentage (0.0 – 1.0)               → 3P%
ftm                       : float - Free throws made per game                         → FTM
free_throw_pct            : float - Free-throw percentage (0.0 – 1.0)                → FT%
rebounds_per_game         : float - Average total rebounds per game                   → Reb
assists_per_game          : float - Average assists per game                          → Ast
steals_per_game           : float - Average steals per game                           → STL
blocks_per_game           : float - Average blocks per game                           → BLK
turnovers_per_game        : float - Average turnovers per game                        → TO

Optional fields (improve projection accuracy when provided)
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
minutes_per_game          : float - Average minutes per game (optional)
home_points_per_game      : float - Points per game at home (optional)
away_points_per_game      : float - Points per game on the road (optional)
last_5_points             : list  - Points in each of the last 5 games (optional)
last_5_rebounds           : list  - Rebounds in each of the last 5 games (optional)
last_5_assists            : list  - Assists in each of the last 5 games (optional)

Example entry (uncomment and fill in real values):
--------------------------------------------------
{
    "team": "Team Name",
    "name": "Player Name",
    "position": "PG",
    "games_played": 50,
    "points_per_game": 25.4,
    "fgm": 9.8,
    "field_goal_pct": 0.471,
    "three_pointers_per_game": 2.8,
    "three_pointers_attempted": 7.4,
    "three_point_pct": 0.378,
    "ftm": 3.0,
    "free_throw_pct": 0.856,
    "rebounds_per_game": 5.1,
    "assists_per_game": 8.3,
    "steals_per_game": 1.4,
    "blocks_per_game": 0.4,
    "turnovers_per_game": 2.9,
},
"""

# ============================================================
# Add your players below. Each entry follows the format above.
# ============================================================

PLAYERS = [
    # ---------------------------------------------------------------
    # Boston Celtics — 2025-26 season per-game averages
    # Source: Props Madness (https://propsmadness.com)
    # ---------------------------------------------------------------
    {
        "team": "Boston Celtics",
        "name": "Jaylen Brown",
        "position": "SG",
        "games_played": 60,
        "minutes_per_game": 34.0,
        "points_per_game": 28.2,
        "fgm": 10.4,
        "field_goal_pct": 0.478,
        "three_pointers_per_game": 2.0,
        "three_pointers_attempted": 5.7,
        "three_point_pct": 0.342,
        "ftm": 5.5,
        "free_throw_pct": 0.787,
        "rebounds_per_game": 7.1,
        "assists_per_game": 5.1,
        "steals_per_game": 1.0,
        "blocks_per_game": 0.4,
        "turnovers_per_game": 3.6,
    },
    {
        "team": "Boston Celtics",
        "name": "Jayson Tatum",
        "position": "SF",
        "games_played": 4,
        "minutes_per_game": 28.3,
        "points_per_game": 19.8,
        "fgm": 7.5,
        "field_goal_pct": 0.400,
        "three_pointers_per_game": 2.8,
        "three_pointers_attempted": 10.0,
        "three_point_pct": 0.275,
        "ftm": 2.0,
        "free_throw_pct": 0.889,
        "rebounds_per_game": 8.5,
        "assists_per_game": 4.5,
        "steals_per_game": 1.3,
        "blocks_per_game": 0.0,
        "turnovers_per_game": 1.3,
    },
    {
        "team": "Boston Celtics",
        "name": "Derrick White",
        "position": "SG",
        "games_played": 64,
        "minutes_per_game": 34.4,
        "points_per_game": 17.4,
        "fgm": 6.0,
        "field_goal_pct": 0.393,
        "three_pointers_per_game": 2.9,
        "three_pointers_attempted": 8.7,
        "three_point_pct": 0.327,
        "ftm": 2.6,
        "free_throw_pct": 0.903,
        "rebounds_per_game": 4.5,
        "assists_per_game": 5.7,
        "steals_per_game": 1.2,
        "blocks_per_game": 1.4,
        "turnovers_per_game": 1.8,
    },
    {
        "team": "Boston Celtics",
        "name": "Payton Pritchard",
        "position": "PG",
        "games_played": 65,
        "minutes_per_game": 32.6,
        "points_per_game": 16.6,
        "fgm": 6.3,
        "field_goal_pct": 0.456,
        "three_pointers_per_game": 2.5,
        "three_pointers_attempted": 7.1,
        "three_point_pct": 0.356,
        "ftm": 1.5,
        "free_throw_pct": 0.868,
        "rebounds_per_game": 4.1,
        "assists_per_game": 5.3,
        "steals_per_game": 0.8,
        "blocks_per_game": 0.1,
        "turnovers_per_game": 1.3,
    },
    {
        "team": "Boston Celtics",
        "name": "Anfernee Simons",
        "position": "SG",
        "games_played": 49,
        "minutes_per_game": 24.5,
        "points_per_game": 14.2,
        "fgm": 5.1,
        "field_goal_pct": 0.440,
        "three_pointers_per_game": 2.7,
        "three_pointers_attempted": 6.7,
        "three_point_pct": 0.395,
        "ftm": 1.3,
        "free_throw_pct": 0.889,
        "rebounds_per_game": 2.4,
        "assists_per_game": 2.4,
        "steals_per_game": 0.6,
        "blocks_per_game": 0.1,
        "turnovers_per_game": 1.1,
    },
    {
        "team": "Boston Celtics",
        "name": "Nikola Vucevic",
        "position": "C",
        "games_played": 12,
        "minutes_per_game": 21.7,
        "points_per_game": 10.4,
        "fgm": 4.1,
        "field_goal_pct": 0.445,
        "three_pointers_per_game": 1.1,
        "three_pointers_attempted": 3.1,
        "three_point_pct": 0.351,
        "ftm": 1.2,
        "free_throw_pct": 0.824,
        "rebounds_per_game": 7.2,
        "assists_per_game": 1.8,
        "steals_per_game": 0.4,
        "blocks_per_game": 0.8,
        "turnovers_per_game": 0.9,
    },
    {
        "team": "Boston Celtics",
        "name": "Neemias Queta",
        "position": "C",
        "games_played": 63,
        "minutes_per_game": 25.0,
        "points_per_game": 10.0,
        "fgm": 4.2,
        "field_goal_pct": 0.639,
        "three_pointers_per_game": 0.0,
        "three_pointers_attempted": 0.1,
        "three_point_pct": 0.000,
        "ftm": 1.6,
        "free_throw_pct": 0.689,
        "rebounds_per_game": 8.4,
        "assists_per_game": 1.4,
        "steals_per_game": 0.8,
        "blocks_per_game": 1.3,
        "turnovers_per_game": 1.1,
    },
    {
        "team": "Boston Celtics",
        "name": "Sam Hauser",
        "position": "SF",
        "games_played": 64,
        "minutes_per_game": 24.7,
        "points_per_game": 9.3,
        "fgm": 3.3,
        "field_goal_pct": 0.409,
        "three_pointers_per_game": 2.6,
        "three_pointers_attempted": 6.8,
        "three_point_pct": 0.388,
        "ftm": 0.2,
        "free_throw_pct": 0.929,
        "rebounds_per_game": 3.9,
        "assists_per_game": 1.5,
        "steals_per_game": 0.6,
        "blocks_per_game": 0.3,
        "turnovers_per_game": 0.5,
    },
    {
        "team": "Boston Celtics",
        "name": "Luka Garza",
        "position": "C",
        "games_played": 57,
        "minutes_per_game": 15.7,
        "points_per_game": 7.3,
        "fgm": 2.6,
        "field_goal_pct": 0.568,
        "three_pointers_per_game": 0.7,
        "three_pointers_attempted": 1.7,
        "three_point_pct": 0.433,
        "ftm": 1.3,
        "free_throw_pct": 0.765,
        "rebounds_per_game": 3.8,
        "assists_per_game": 1.0,
        "steals_per_game": 0.4,
        "blocks_per_game": 0.4,
        "turnovers_per_game": 0.6,
    },
    {
        "team": "Boston Celtics",
        "name": "Josh Minott",
        "position": "SF",
        "games_played": 33,
        "minutes_per_game": 15.9,
        "points_per_game": 5.8,
        "fgm": 2.1,
        "field_goal_pct": 0.507,
        "three_pointers_per_game": 1.0,
        "three_pointers_attempted": 2.3,
        "three_point_pct": 0.442,
        "ftm": 0.6,
        "free_throw_pct": 0.769,
        "rebounds_per_game": 3.6,
        "assists_per_game": 1.0,
        "steals_per_game": 0.7,
        "blocks_per_game": 0.4,
        "turnovers_per_game": 0.6,
    },
    {
        "team": "Boston Celtics",
        "name": "Jordan Walsh",
        "position": "SG",
        "games_played": 58,
        "minutes_per_game": 17.2,
        "points_per_game": 5.3,
        "fgm": 2.0,
        "field_goal_pct": 0.525,
        "three_pointers_per_game": 0.7,
        "three_pointers_attempted": 1.7,
        "three_point_pct": 0.408,
        "ftm": 0.6,
        "free_throw_pct": 0.750,
        "rebounds_per_game": 4.1,
        "assists_per_game": 0.7,
        "steals_per_game": 0.7,
        "blocks_per_game": 0.4,
        "turnovers_per_game": 0.6,
    },
    {
        "team": "Boston Celtics",
        "name": "Baylor Scheierman",
        "position": "SG",
        "games_played": 62,
        "minutes_per_game": 17.2,
        "points_per_game": 4.9,
        "fgm": 1.8,
        "field_goal_pct": 0.449,
        "three_pointers_per_game": 1.1,
        "three_pointers_attempted": 2.9,
        "three_point_pct": 0.379,
        "ftm": 0.3,
        "free_throw_pct": 0.889,
        "rebounds_per_game": 3.4,
        "assists_per_game": 1.3,
        "steals_per_game": 0.5,
        "blocks_per_game": 0.1,
        "turnovers_per_game": 0.6,
    },
    {
        "team": "Boston Celtics",
        "name": "Hector Gonzalez",
        "position": "PG",
        "games_played": 62,
        "minutes_per_game": 15.5,
        "points_per_game": 4.2,
        "fgm": 1.7,
        "field_goal_pct": 0.475,
        "three_pointers_per_game": 0.6,
        "three_pointers_attempted": 1.7,
        "three_point_pct": 0.340,
        "ftm": 0.2,
        "free_throw_pct": 0.500,
        "rebounds_per_game": 3.5,
        "assists_per_game": 0.6,
        "steals_per_game": 0.6,
        "blocks_per_game": 0.3,
        "turnovers_per_game": 0.5,
    },
    {
        "team": "Boston Celtics",
        "name": "Ron Harper Jr.",
        "position": "SG",
        "games_played": 21,
        "minutes_per_game": 11.4,
        "points_per_game": 3.9,
        "fgm": 1.4,
        "field_goal_pct": 0.400,
        "three_pointers_per_game": 1.0,
        "three_pointers_attempted": 2.9,
        "three_point_pct": 0.344,
        "ftm": 0.0,
        "free_throw_pct": 0.500,
        "rebounds_per_game": 1.7,
        "assists_per_game": 0.7,
        "steals_per_game": 0.2,
        "blocks_per_game": 0.4,
        "turnovers_per_game": 0.2,
    },
    {
        "team": "Boston Celtics",
        "name": "Chris Boucher",
        "position": "PF",
        "games_played": 9,
        "minutes_per_game": 10.4,
        "points_per_game": 2.3,
        "fgm": 0.9,
        "field_goal_pct": 0.320,
        "three_pointers_per_game": 0.2,
        "three_pointers_attempted": 1.7,
        "three_point_pct": 0.133,
        "ftm": 0.3,
        "free_throw_pct": 0.750,
        "rebounds_per_game": 2.0,
        "assists_per_game": 0.3,
        "steals_per_game": 0.6,
        "blocks_per_game": 0.8,
        "turnovers_per_game": 0.1,
    },
    {
        "team": "Boston Celtics",
        "name": "Xavier Tillman",
        "position": "PF",
        "games_played": 14,
        "minutes_per_game": 7.9,
        "points_per_game": 2.2,
        "fgm": 1.0,
        "field_goal_pct": 0.452,
        "three_pointers_per_game": 0.2,
        "three_pointers_attempted": 1.1,
        "three_point_pct": 0.200,
        "ftm": 0.0,
        "free_throw_pct": 0.000,
        "rebounds_per_game": 1.8,
        "assists_per_game": 0.4,
        "steals_per_game": 0.4,
        "blocks_per_game": 0.1,
        "turnovers_per_game": 0.4,
    },
    {
        "team": "Boston Celtics",
        "name": "Dalano Banton",
        "position": "SF",
        "games_played": 3,
        "minutes_per_game": 5.0,
        "points_per_game": 1.3,
        "fgm": 0.3,
        "field_goal_pct": 0.200,
        "three_pointers_per_game": 0.0,
        "three_pointers_attempted": 0.0,
        "three_point_pct": 0.000,
        "ftm": 0.7,
        "free_throw_pct": 1.000,
        "rebounds_per_game": 0.0,
        "assists_per_game": 0.7,
        "steals_per_game": 0.0,
        "blocks_per_game": 0.3,
        "turnovers_per_game": 0.3,
    },
    {
        "team": "Boston Celtics",
        "name": "Amari Williams",
        "position": "PF",
        "games_played": 19,
        "minutes_per_game": 6.3,
        "points_per_game": 1.3,
        "fgm": 0.4,
        "field_goal_pct": 0.471,
        "three_pointers_per_game": 0.0,
        "three_pointers_attempted": 0.0,
        "three_point_pct": 0.000,
        "ftm": 0.4,
        "free_throw_pct": 0.667,
        "rebounds_per_game": 1.6,
        "assists_per_game": 0.4,
        "steals_per_game": 0.1,
        "blocks_per_game": 0.5,
        "turnovers_per_game": 0.4,
    },
    {
        "team": "Boston Celtics",
        "name": "Jordan Tonje",
        "position": "SG",
        "games_played": 3,
        "minutes_per_game": 3.7,
        "points_per_game": 0.7,
        "fgm": 0.0,
        "field_goal_pct": 0.000,
        "three_pointers_per_game": 0.0,
        "three_pointers_attempted": 0.7,
        "three_point_pct": 0.000,
        "ftm": 0.7,
        "free_throw_pct": 1.000,
        "rebounds_per_game": 0.7,
        "assists_per_game": 0.3,
        "steals_per_game": 0.0,
        "blocks_per_game": 0.0,
        "turnovers_per_game": 0.0,
    },
    {
        "team": "Boston Celtics",
        "name": "Matas Shulga",
        "position": "PG",
        "games_played": 4,
        "minutes_per_game": 1.5,
        "points_per_game": 0.0,
        "fgm": 0.0,
        "field_goal_pct": 0.000,
        "three_pointers_per_game": 0.0,
        "three_pointers_attempted": 0.0,
        "three_point_pct": 0.000,
        "ftm": 0.0,
        "free_throw_pct": 0.000,
        "rebounds_per_game": 0.0,
        "assists_per_game": 0.0,
        "steals_per_game": 0.0,
        "blocks_per_game": 0.0,
        "turnovers_per_game": 0.0,
    },
]
